export const mockSpeechPayload = {
  visible_text: "I held the line.",
  spoken_text: "I held the line.",
  speech_plan: {
    text: "I held the line.",
    visible_text: "I held the line.",
    spoken_text: "I held the line.",
    posture: "social_continuity",
    signature_phrase: "I held the line.",
    voice_mode: "warm_recall",
    pace: "slow",
    volume: "low_medium",
    pitch_shape: "soft_falling",
    rate: 0.9,
    pause_scale: 1.2,
    pause_before_ms: 350,
    pauses: [
      { after: ".", ms: 240 },
    ],
    emphasis: ["held"],
    pronunciation_overrides: [],
    voice_mode_config: {
      mode: "warm_recall",
      rate: 0.9,
      volume: "low_medium",
      pause_scale: 1.2,
      pitch_shape: "gentle_falling",
    },
    signature_phrase_config: {
      phrase: "I held the line.",
      voice_mode: "warm_recall",
      pace: "slow",
      pitch_shape: "soft_falling",
      pause_before_ms: 350,
      emphasis: ["held"],
    },
    safety: {
      content_unchanged: true,
      assertion_added: false,
    },
  },
  piper_render_request: {
    text: "I held the line.",
    spoken_text: "I held the line.",
    render_text: "I held the line.",
    voice_mode: "warm_recall",
    rate: 0.9,
    volume: "low_medium",
    pause_scale: 1.2,
    pause_before_ms: 350,
    ignored_metadata: [],
  },
  avatar_cues: {
    voice_mode: "warm_recall",
    pace: "slow",
    pause_before_ms: 350,
    emphasis: ["held"],
    private_mode: false,
    quiet_private: false,
    signature_phrase: "I held the line.",
  },
} as const;

export type SpeechDebugPayload = typeof mockSpeechPayload;
